import type { Metadata } from "next";
import { Suspense } from "react";
import { inter } from "@/app/ui/fonts";
import { SessionProvider } from "next-auth/react";
import AppTheme from "@/shared-theme/AppTheme";
import CssBaseline from "@mui/material/CssBaseline";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: any;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AppTheme>
          <CssBaseline enableColorScheme />
          <SessionProvider session={session}>
            <Suspense fallback={<p>Loading...</p>}>{children}</Suspense>
          </SessionProvider>
        </AppTheme>
      </body>
    </html>
  );
}
